# Lecture 11 – Grouping

## Data 6, Summer 2025

In [3]:
from datascience import *
import numpy as np
%matplotlib inline
Table.interactive_plots()

## Grouping with `.group`

The term "group" in data science is most commonly associated with data aggregation and disaggregation. When we "group" a table in Python, we are able to gain insights about our data at a higher unit of analysis (e.g. at a city or state level, as opposed to the individual level).

Returning to the `top_10` dataset from last week (showing the songs on the Spotify Top 10), we can utilize `tbl.group()` to count how many Top 10 songs each artist has.

In [4]:
top_10 = Table.read_table('data/regional-global-daily-latest.csv').take(np.arange(10))
top_10

rank | artist_names                 | track_name                              | source                        | peak_rank | previous_rank | days_on_chart | streams
1    | Kate Bush                    | Running Up That Hill                    | Rhino                         | 1         | 1             | 41            | 7208654
2    | Harry Styles                 | As It Was                               | Columbia                      | 1         | 2             | 99            | 6543793
3    | Joji                         | Glimpse of Us                           | 88rising Music/Warner Records | 1         | 3             | 28            | 5492997
4    | Bad Bunny, Chencho Corleone  | Me Porto Bonito                         | Rimas Entertainment LLC       | 2         | 4             | 63            | 5416421
5    | Bizarrap, Quevedo            | Quevedo: Bzrp Music Sessions, Vol. 52   | DALE PLAY Records             | 5         | -1            | 1             | 4676471
6    | Bad Bunny                    | Tití Me Preguntó                        | Rimas Entertainment LLC       | 4         | 5             | 63            | 4549682
7    | Bad Bunny, Bomba Estéreo     | Ojitos Lindos                           | Rimas Entertainment LLC       | 2         | 6             | 63            | 4144625
8    | Bad Bunny                    | Efecto                                  | Rimas Entertainment LLC       | 7         | 8             | 63            | 3722317
9    | Charlie Puth, BTS, Jung Kook | Left and Right (Feat. Jung Kook of BTS) | Atlantic Records              | 3         | 7             | 14            | 3715689
10   | Bad Bunny                    | Moscow Mule                             | Rimas Entertainment LLC       | 1         | 9             | 63            | 3465003

By default `tbl.group(column)` counts the number of occurences of each unique value in `column`.

In [5]:
top_10.group("artist_names").sort("count", descending = True) # Group `top_10` by artist name and then sort by count

artist_names                 | count
Bad Bunny                    | 3
Bad Bunny, Bomba Estéreo     | 1
Bad Bunny, Chencho Corleone  | 1
Bizarrap, Quevedo            | 1
Charlie Puth, BTS, Jung Kook | 1
Harry Styles                 | 1
Joji                         | 1
Kate Bush                    | 1

Notice that Bad Bunny's name appears 5 times on the Top 10, but the "Bad Bunny" row in the grouped table only has a count of 3. This is because Python looks for an **exact match**. The songs where Bad Bunny appears along with other artists are counted separately.

### Quick Check

In [6]:
streams = Table.read_table('data/regional-global-daily-latest.csv')
streams

rank | artist_names                 | track_name                              | source                        | peak_rank | previous_rank | days_on_chart | streams
1    | Kate Bush                    | Running Up That Hill                    | Rhino                         | 1         | 1             | 41            | 7208654
2    | Harry Styles                 | As It Was                               | Columbia                      | 1         | 2             | 99            | 6543793
3    | Joji                         | Glimpse of Us                           | 88rising Music/Warner Records | 1         | 3             | 28            | 5492997
4    | Bad Bunny, Chencho Corleone  | Me Porto Bonito                         | Rimas Entertainment LLC       | 2         | 4             | 63            | 5416421
5    | Bizarrap, Quevedo            | Quevedo: Bzrp Music Sessions, Vol. 52   | DALE PLAY Records             | 5         | -1            | 1             | 4676471
6    | Bad Bunny                    | Tití Me Preguntó                        | Rimas Entertainment LLC       | 4         | 5             | 63            | 4549682
7    | Bad Bunny, Bomba Estéreo     | Ojitos Lindos                           | Rimas Entertainment LLC       | 2         | 6             | 63            | 4144625
8    | Bad Bunny                    | Efecto                                  | Rimas Entertainment LLC       | 7         | 8             | 63            | 3722317
9    | Charlie Puth, BTS, Jung Kook | Left and Right (Feat. Jung Kook of BTS) | Atlantic Records              | 3         | 7             | 14            | 3715689
10   | Bad Bunny                    | Moscow Mule                             | Rimas Entertainment LLC       | 1         | 9             | 63            | 3465003
... (190 rows omitted)

Using the `streams` table, fill in the blanks to create the “Top 10 Artists”: The 10 artists with the most songs in the Spotify Daily Top 200 streams table.

In [7]:
top_10_artists = streams.group(...).sort(..., descending=True).take(...)
top_10_artists

artist_names    | count
Bad Bunny       | 16
Harry Styles    | 8
Olivia Rodrigo  | 5
The Weeknd      | 5
Ed Sheeran      | 4
Arctic Monkeys  | 3
BTS             | 3
Doja Cat        | 3
Eminem          | 3
Imagine Dragons | 3

## Advanced Grouping

For the rest of today's lecture, we will use the `cars` table, which contains specifications for a variety of car models.

In [9]:
cars = Table.read_table('data/models-2021.csv')
cars

Manufacturer | Brand | Model                   | Displacement | Cylinders | MPG  | Wheel
BMW          | BMW   | 228i Gran Coupe         | 2            | 4         | 28   | 2-Wheel Drive, Front
BMW          | BMW   | 228i xDrive Gran Coupe  | 2            | 4         | 27   | All Wheel Drive
BMW          | BMW   | 230i Convertible        | 2            | 4         | 27   | 2-Wheel Drive, Rear
BMW          | BMW   | 230i Coupe              | 2            | 4         | 28   | 2-Wheel Drive, Rear
BMW          | BMW   | 230i xDrive Convertible | 2            | 4         | 24   | All Wheel Drive
BMW          | BMW   | 230i xDrive Coupe       | 2            | 4         | 24   | All Wheel Drive
BMW          | BMW   | 330i                    | 2            | 4         | 30   | 2-Wheel Drive, Rear
BMW          | BMW   | 330i xDrive             | 2            | 4         | 28   | All Wheel Drive
BMW          | BMW   | 430i Coupe              | 2            | 4         | 29   | 2-Wheel Drive, Rear
BMW          | BMW   | 430i xDrive Coupe       | 2            | 4         | 27   | All Wheel Drive
... (764 rows omitted)

A few notes:
* `Manufacturer` is who owns the Brand.
    * GM owns Buick, Cadillac, Chevrolet, GMC.
* `Displacement` is the engine size in liters.
* `MPG` is miles per gallon.

Here we'll take a subset of the rows and columns for illustration.

In [7]:
gm = cars.where('Manufacturer', 'General Motors').select('Brand', 'Model', 'Cylinders', 'MPG').take([0, 1, 9, 16, 20, 30, 31, 35, -1]).take([1, 2, 4, 8, 5, 6, 3, 7, 0])
gm

Brand     | Model        | Cylinders | MPG
Buick     | ENCLAVE FWD  | 6         | 21
Cadillac  | CT4 AWD      | 4         | 26
Cadillac  | XT5 AWD      | 4         | 23
GMC       | YUKON XL 4WD | 6         | 22
Chevrolet | CAMARO       | 4         | 25
Chevrolet | COLORADO 2WD | 4         | 22
Cadillac  | ESCALADE 2WD | 6         | 23
Chevrolet | EQUINOX AWD  | 4         | 27
Buick     | ENCLAVE AWD  | 6         | 20

### Default Behavior

We have already seen how we can group on a single variable/column.

In [8]:
gm.group("Brand") # Group `gm` by Brand

Brand     | count
Buick     | 2
Cadillac  | 3
Chevrolet | 3
GMC       | 1

In [9]:
gm.group("Cylinders") # Group `gm` by number of Cylinders

Cylinders | count
4         | 5
6         | 4

In [12]:
# shuffles the rows in the table; returns a new table
cars.shuffle()

Manufacturer        | Brand                            | Model                 | Displacement | Cylinders | MPG  | Wheel
Toyota              | LEXUS                            | ES 250 AWD            | 2.5          | 4         | 28   | All Wheel Drive
Jaguar Land Rover L | Jaguar                           | F-TYPE S AWD Coupe    | 3            | 6         | 21   | All Wheel Drive
Kia                 | KIA MOTORS CORPORATION           | Rio                   | 1.6          | 4         | 36   | 2-Wheel Drive, Front
Nissan              | NISSAN                           | KICKS                 | 1.6          | 4         | 33   | 2-Wheel Drive, Front
General Motors      | Cadillac                         | CT5                   | 2            | 4         | 26   | 2-Wheel Drive, Rear
MAZDA               | MAZDA                            | MAZDA2                | 1.5          | 4         | 35   | 2-Wheel Drive, Front
Hyundai             | HYUNDAI MOTOR COMPANY            | Ioniq                 | 1.6          | 4         | 55   | 2-Wheel Drive, Front
Toyota              | TOYOTA                           | HIGHLANDER HYBRID AWD | 2.5          | 4         | 35   | All Wheel Drive
Volvo               | Volvo Cars of North America, LLC | XC60 FWD              | 2            | 4         | 25   | 2-Wheel Drive, Front
Toyota              | LEXUS                            | UX 250h               | 2            | 4         | 42   | 2-Wheel Drive, Front
... (764 rows omitted)

In [13]:
cars.group('Brand')

Brand                    | count
ALFA ROMEO               | 4
Acura                    | 10
Aston Martin Lagonda Ltd | 6
Audi                     | 41
BMW                      | 76
Bentley                  | 4
Bugatti                  | 2
Buick                    | 8
Cadillac                 | 20
Chevrolet                | 27
... (31 rows omitted)

Note that it doesn't matter what order the rows are originally in. The resulting table will be sorted alphabetically.

### Specifying a `collect` function

We can also use `.group` to learn other aggregate statistics about cateogories. We do this by specifying a second argument: `collect`. The `collect` argument must be a function (e.g. `len`, `min` `np.mean`, etc).

In [14]:
... # Group `gm` by Brand and use np.mean as the collect function

Ellipsis

How does this work under the hood?

In [15]:
gm.where('Brand', 'Buick')

Brand | Model       | Cylinders | MPG
Buick | ENCLAVE FWD | 6         | 21
Buick | ENCLAVE AWD | 6         | 20

In [16]:
print('mean of Cylinders: ', gm.where('Brand', 'Buick').column('Cylinders').mean())
print('mean of MPG: ', gm.where('Brand', 'Buick').column('MPG').mean())

mean of Cylinders:  6.0
mean of MPG:  20.5

In [17]:
gm.where('Brand', 'Cadillac')

Brand    | Model        | Cylinders | MPG
Cadillac | CT4 AWD      | 4         | 26
Cadillac | XT5 AWD      | 4         | 23
Cadillac | ESCALADE 2WD | 6         | 23

In [18]:
print('mean of Cylinders: ', gm.where('Brand', 'Cadillac').column('Cylinders').mean())
print('mean of MPG: ', gm.where('Brand', 'Cadillac').column('MPG').mean())

mean of Cylinders:  4.66666666667
mean of MPG:  24.0

In [19]:
gm.where('Brand', 'Chevrolet')

Brand     | Model        | Cylinders | MPG
Chevrolet | CAMARO       | 4         | 25
Chevrolet | COLORADO 2WD | 4         | 22
Chevrolet | EQUINOX AWD  | 4         | 27

In [20]:
print('mean of Cylinders: ', gm.where('Brand', 'Chevrolet').column('Cylinders').mean())
print('mean of MPG: ', gm.where('Brand', 'Chevrolet').column('MPG').mean())

mean of Cylinders:  4.0
mean of MPG:  24.6666666667

In [21]:
gm.where('Brand', 'GMC')

Brand | Model        | Cylinders | MPG
GMC   | YUKON XL 4WD | 6         | 22

In [22]:
print('mean of Cylinders: ', gm.where('Brand', 'GMC').column('Cylinders').mean())
print('mean of MPG: ', gm.where('Brand', 'GMC').column('MPG').mean())

mean of Cylinders:  6.0
mean of MPG:  22.0

If you want a more concise way of doing the above:

In [23]:
# Just run this cell — you'll learn how to write for loops next week
for brand in np.unique(gm.column('Brand')):
    brand_only = gm.where('Brand', brand)
    print(brand)
    print('mean of Cylinders: ', brand_only.column('Cylinders').mean())
    print('mean of MPG: ', brand_only.column('MPG').mean())
    print('\n')

Buick
mean of Cylinders:  6.0
mean of MPG:  20.5


Cadillac
mean of Cylinders:  4.66666666667
mean of MPG:  24.0


Chevrolet
mean of Cylinders:  4.0
mean of MPG:  24.6666666667


GMC
mean of Cylinders:  6.0
mean of MPG:  22.0

What if we use other `collect` functions?

In [24]:
gm

Brand     | Model        | Cylinders | MPG
Buick     | ENCLAVE FWD  | 6         | 21
Cadillac  | CT4 AWD      | 4         | 26
Cadillac  | XT5 AWD      | 4         | 23
GMC       | YUKON XL 4WD | 6         | 22
Chevrolet | CAMARO       | 4         | 25
Chevrolet | COLORADO 2WD | 4         | 22
Cadillac  | ESCALADE 2WD | 6         | 23
Chevrolet | EQUINOX AWD  | 4         | 27
Buick     | ENCLAVE AWD  | 6         | 20

In [25]:
gm.group('Brand', sum)

Brand     | Model sum | Cylinders sum | MPG sum
Buick     |           | 12            | 41
Cadillac  |           | 14            | 72
Chevrolet |           | 12            | 74
GMC       |           | 6             | 22

In [26]:
gm.group('Brand', list)

Brand     | Model list                                | Cylinders list | MPG list
Buick     | ['ENCLAVE FWD', 'ENCLAVE AWD']            | [6, 6]         | [21, 20]
Cadillac  | ['CT4 AWD', 'XT5 AWD', 'ESCALADE 2WD']    | [4, 4, 6]      | [26, 23, 23]
Chevrolet | ['CAMARO', 'COLORADO 2WD', 'EQUINOX AWD'] | [4, 4, 4]      | [25, 22, 27]
GMC       | ['YUKON XL 4WD']                          | [6]            | [22]

In [27]:
gm.group('Brand', len)

Brand     | Model len | Cylinders len | MPG len
Buick     | 2         | 2             | 2
Cadillac  | 3         | 3             | 3
Chevrolet | 3         | 3             | 3
GMC       | 1         | 1             | 1

In [28]:
gm.group('Brand', max)

Brand     | Model max    | Cylinders max | MPG max
Buick     | ENCLAVE FWD  | 6             | 21
Cadillac  | XT5 AWD      | 6             | 26
Chevrolet | EQUINOX AWD  | 4             | 27
GMC       | YUKON XL 4WD | 6             | 22

Ta-da!